### ISSUE TITLE
Cannot cache

### ISSUE THREAD

**Issue by RetroZelda** [edv/docker-spotweb#70]
From the README:
```To retain this cache you can mount a volume to /app/cache see the commented lines in the included Docker Compose files on how to do this```

This is a lie.  The docker compose examples dont include this information.

Putting this in the docker compose
```
volumes:
      - ./data:/data
      - ./cache:/app/cache
```

Results in `Cache directory is writable?	NOT OK` displayed in install.php

**Comment by robvanoostenrijk** [comment]
Bit rude to suggest a possible documentation error is a lie.

However, the functionality seems to be working just fine. I have spotweb running as part of a runtipi installation:

```
version: "3.7"
services:
  spotweb:
    image: erikdevries/spotweb:sha-2ffd438
    container_name: spotweb
    environment:
      - CRON_INTERVAL=${SPOTWEB_CRON_INTERVAL}
      - DB_ENGINE=${SPOTWEB_DB_ENGINE}
      - DB_HOST=${SPOTWEB_DB_HOST}
      - DB_NAME=${SPOTWEB_DB_NAME}
      - DB_PASS=${SPOTWEB_DB_PASS}
      - DB_PORT=${SPOTWEB_DB_PORT}
      - DB_USER=${SPOTWEB_DB_USER}
      - TZ=${TZ}
    dns:
      - ${DNS_IP}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/cache:/app/cache
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    networks:
      - tipi_main_network
 ....
```

```
docker:/opt/runtipi/app-data/spotweb/cache# ls
image  nzb    stats  web
```

<img width="601" alt="Image" src="https://github.com/user-attachments/assets/f02bf012-fbcc-448b-9e2f-e21805801efd" />

Whatever issue you are experiencing, it does not seem to be part of docker-spotweb.
From the looks of it, its a permission mismatch between the uid that spotweb is using and the uid that has access to that folder on your docker host.
