### ISSUE TITLE
DB_HOST isn't being resolved by 'spotweb' container.

### ISSUE THREAD

**Issue by lvanoverberghe** [edv/docker-spotweb#76]
I'm using the latest version and I'm getting the following errors:

Waiting (5 seconds) for database connection at host 'spotweb_db:3306'... 
nc: bad address 'spotweb_db' 

![Image](https://github.com/user-attachments/assets/f90d8ec2-eb99-4df7-b872-0ae3f5b901bf)

**Comment by KoalaBear84** [comment]
I'm not an expert of docker-spotweb, but I guess the information in the issue is not sufficient to say something usefull about a the possible issue.

Do you use a docker compose? If you are only using the spotweb image/container 'directly', without a DB container/image, I guess that is the issue.

Spotweb also needs a container with a database to save the spots in.

See https://github.com/edv/docker-spotweb?tab=readme-ov-file#getting-started

**Comment by lvanoverberghe** [comment]
Yes, I'm using Docker Compose. It was working fine just a couple of days ago, but I upgraded to latest version and this error came up. Here is my Docker Compose. It works when I substitute the spotweb_db with the actual IP after building. 

```
version: 'latest'
services:
  spotweb:
    image: erikdevries/spotweb
    container_name: spotweb
    environment:
      - TZ=Europe/xxx 
      - DB_PORT=xxx
      - DB_HOST=spotweb_db (or xxx.xxx.xxx.xxx)
      - DB_NAME=spotweb
      - DB_USER=xxx
      - DB_PASS=xxxxx 
      - CRON_INTERVAL=*/5 * * * *
    ports:
      - 8085:80/tcp
    network_mode: bridge
    depends_on:
      - spotweb_db
    security_opt:
      - no-new-privileges:true
    restart: always

  spotweb_db:
    image: linuxserver/mariadb:latest
    container_name: spotweb_db
    environment:
      - MYSQL_ROOT_PASSWORD=xxxx
      - PUID=1026 
      - PGID=100 
      - TZ=Europe/xxx 
      - MYSQL_DATABASE=spotweb
      - MYSQL_USER=xxx 
      - MYSQL_PASSWORD=xxxxx
    volumes:
      - /volume1/docker/spotweb-mariadb:/config
    ports:
      - 3306:3306/tcp
    network_mode: bridge
    security_opt:
      - no-new-privileges:true
    restart: always
```
